edificios/urls.py
from django.urls import path
from .views import EdificiosHomeView,AgregarView,eliminar,editar

app_name='edificios'

urlpatterns = [
    path('', EdificiosHomeView, name='home'),
    path('agregar/',AgregarView.as_view(),name="agregar"),
    path('eliminar/<int:id>', eliminar),
    path('editar/<int:id>',editar),

]

gescon/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, cerrarSesion
from edificios.urls import *
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomeView,name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('salir/',cerrarSesion,name='salir'),
    path('edificios/',include('edificios.urls', namespace='edificios')),
    # path('propietarios/',include('propietarios.urls', namespace='propietarios')),
    # path('departamentos/',include('departamentos.urls', namespace='departamentos')),
        
]

edificios/models.py
from django.db import models

# Create your models here.

modelos/models.py
from django.db import models
from usuarios.models import Usuario

# definimos modelo Propietarios
class Propietarios(models.Model):
    id=models.IntegerField(primary_key=True,serialize=True)
    nombre=models.CharField(max_length=45,verbose_name="Nombre")
    apellido=models.CharField(max_length=45,verbose_name="Apellido")
    domicilio=models.CharField(max_length=45, verbose_name="Domicilio",blank=True,null=True)
    contacto=models.CharField(max_length=15,verbose_name="Tel. de Contacto",blank=True,null=True)
    email=models.EmailField(verbose_name="Correo Electrónico",blank=True,null=True)
    cuit_cuil=models.CharField(max_length=15,blank=False, null=False,verbose_name="CUIT/CUIL")
    
    class Meta:
        db_table='propietarios'

# definimos modelo Edificios
class Edificios(models.Model):
    id=models.IntegerField(primary_key=True,serialize=True)
    nombre=models.CharField(max_length=45,verbose_name="Nombre Edificio")
    domicilio=models.CharField(max_length=45, verbose_name="Domicilio")
    cantidad_dptos=models.IntegerField()
    administrador=models.ForeignKey(Usuario,on_delete=models.CASCADE)
    
    class Meta:
        db_table='edificios'


# definimos modelo Departamentos
class Departamentos(models.Model):
    id=models.IntegerField(primary_key=True,serialize=True)
    piso=models.IntegerField(verbose_name="Nro. de Piso")
    numero=models.CharField(max_length=2,blank=False, null=False,verbose_name="Nro. Departamento")
    propietario=models.ForeignKey(Propietarios,on_delete=models.CASCADE)
    edificio=models.ForeignKey(Edificios,on_delete=models.CASCADE)
    porcentaje=models.DecimalField(max_digits=5,decimal_places=2,verbose_name="Porcentaje expensas")

    class Meta:
        db_table='departamentos'

usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

# Create your models here.

# definimos el user manager
class UsuarioManager(BaseUserManager):
    def create_user(self, email,username,nombre,apellidos,password=None):
        if not email:
            raise ValueError('El usuario debe tener un Correo Electrónico!')
        
        usuario = self.model(
            username = username,
            email = self.normalize_email(email),
            nombre = nombre,
            apellidos = apellidos
        )

        usuario.set_password(password)
        usuario.save()
        return usuario

    def create_superuser(self, email,username,nombre,apellidos,password=None):
               
        usuario = self.create_user(
            email,
            username = username,
            nombre = nombre,
            apellidos = apellidos,
            password=password
        )

        usuario.usuario_administrador = True

        usuario.save()
        return usuario
    
# definimos modelo User        
class Usuario(AbstractBaseUser):
    username=models.CharField('Nombre de Usuario', max_length=10, unique=True)
    email=models.EmailField('Correo Electrónico',unique=True,max_length=255)
    nombre=models.CharField('Nombre',max_length=100, blank=True, null=True)
    apellidos=models.CharField('Apellidos',max_length=100, blank=True,null=True)
    usuario_activo=models.BooleanField(default=True)
    usuario_administrador=models.BooleanField(default=False)

    objects=UsuarioManager()

    USERNAME_FIELD ='username'
    REQUIRED_FIELDS = ['email','nombre','apellidos']

    def __str__(self):
        return f'{self.nombre},{self.apellidos}'
    
    def has_perm(self,perm,obj=None):
        return True

    def has_module_perms(self,app_label):
        return True
    @property
    def is_staff(self):
        return self.usuario_administrador

    class Meta:
        db_table='usuario'

edificios/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from modelos.models import Edificios
from usuarios.models import Usuario

# Create your views here.

def EdificiosHomeView(request):    
    user=request.user
    edificios=Edificios.objects.filter(administrador=user.id)
    return render(request, 'edificios/index.html',{'edificios':edificios})        

class AgregarView(View):
    def get(self,request,*args, **kwargs):
        
        usuarios=Usuario.objects.all()
        context={
            'usuarios':usuarios,
        }
        return render(request,'edificios/agregar.html',context)   

    def post(self,request,*args,**kwargs):
        user=request.user
        print(user)
        edificio=Edificios()
        edificio.nombre=request.POST.get('nombre')
        edificio.domicilio=request.POST.get('domicilio')
        edificio.administrador=user.id
        edificio.save()
        return redirect('edificios:home')
            
def eliminar(request, id):
    edificio=Edificios.objects.get(id=id)
    edificio.delete()
    
    return redirect('edificios:home')

def editar(request, id):
    
    edificio=Edificios.objects.get(id=id) 
    
    if request.method=="POST":

        edificio.nombre=request.POST.get('nombre')
        edificio.domicilio=request.POST.get('domicilio')
        edificio.save()
        return redirect('edificios:home')

    context = {
        'edificio':edificio,
    }
    return render(request, 'edificios/editar.html',context)  

gescon/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

# Create your views here.
@login_required()

def HomeView(request):
       
    return render(request,'index.html',{})

def cerrarSesion(request):
    logout(request)
    return redirect('home')

modelos/views.py
from django.shortcuts import render

# Create your views here.

usuarios/views.py
from django.shortcuts import render

# Create your views here.

templates/departamentos/agregar.html
{% extends 'layout.html' %}
{% block titulo %}
Agregar Departamentos
{% endblock %}
{% block contenido %}
<div class="container">
    <div class="card">
        <div class="card-header" style="background:darkkhaki;">
            Agregar Departamento
        </div>
        <div class="card-body" style="background:bisque;">
          <h4 class="card-title">Datos del Departamento</h4>
   
           {% include "departamentos/form.html" %}
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
{% endblock %}

templates/departamentos/editar.html
{% extends 'layout.html' %}
{% block titulo %}
Editar Departamentos
{% endblock %}
{% block contenido %}
<div class="container">
    <div class="card">
        <div class="card-header" style="background:darkkhaki;">
            Editar Departamentos
        </div>
        <div class="card-body" style="background:bisque;">
          <h4 class="card-title">Datos del Departamento</h4>
   
           {% include "departamentos/form.html" %}
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script>
$(document).ready(function() {

};
</script>
{% endblock %}

templates/departamentos/form.html
<input type="text" name='id_edifico' value="{{ edificio }}">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
      <div class="form-group">
          <label for="piso">Piso</label>
          <input id="piso" class="form-control" type="text" name="piso" value="{{ departamento.piso }}">
      </div>
      <div class="form-group">
          <label for="numero">Número</label>
          <input id="numero" class="form-control" type="text" name="numero" value="{{ departamento.numero }}">
      </div>
      <div class="form-group">
        <label for="propietario">Propietario</label>
        <select id="propietario" name='propietario' class="form-control">
          {% for p in propietarios %}
          <option value="{{ p.id }}">{{ p.nombre}}</option>
          {% endfor %}
        </select> 
      </div>
        <div class="form-group">
        <label for="porcentaje">% Expensas</label>
        <input id="porcentaje" class="form-control" type="text" name="porcentaje" value="{{ departamento.porcentaje }}">
      </div>

  <div class='mb-3 mt-3'>
  <input class="btn btn-primary btn-sm" type="submit" value="Guardar">
  <a href="{% url 'departamentos:home' %}" class='btn btn-sm btn-danger'>Cancelar</a>
  </div>
</form>

templates/departamentos/index.html
{% extends 'layout.html' %}
{% load static %}

{% block titulo %}Departamentos{% endblock %}
{% block contenido %}
    <div class="card">
        <div class="card-body">
            <p class="card-header h3">Listado de Departamentos</p>
            <label>Edificio: </label>
            <select name="edificio_id" id="edificio_id" class="form-control">
                {% for e in edificios %}
                <option value="{{ e.id }}">{{ e.nombre }}</option>
                {% endfor %}
            </select>
            <input type="text" id="id_edificio" name="id_edificio">
            <div id='agrega'></div>
            <table class="table table-striped table-sm table-success" id='departamentos'>
                <thead class="table-dark">
                    <th>Piso</th>
                    <th>Número</th>
                    <th>% Expensas</th>
                    <th>Propietario</th>
                    <th>Acciones</th>
                </thead>
                    <tr>
                        <td>
                            <a href="editar/{{ d.id }}" class='btn btn-sm btn-success'><i class='fa fa-edit'></i> Editar</a>
                            <a href="eliminar/{{ d.id }}" class='btn btn-sm btn-danger'><i class='fa fa-trash'></i> Eliminar</a>
                        </td>
                    </tr>
            
                </table>
        </div>
    </div>
{% endblock contenido %}
{% block js %}
<script src={% static "js/departamentos/functions.js" %}></script>
<script>
  
</script>
{% endblock js %}

templates/edificios/agregar.html
{% extends 'layout.html' %}
{% block titulo %}
Agregar Edifico
{% endblock %}
{% block contenido %}
<div class="container">
    <div class="card">
        <div class="card-header" style="background:darkkhaki;">
            Agregar Edificios
        </div>
        <div class="card-body" style="background:bisque;">
          <h4 class="card-title">Datos del Edificio</h4>
   
           {% include "edificios/form.html" %}
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script>
$(document).ready(function() {

};
</script>
{% endblock %}

templates/edificios/editar.html
{% extends 'layout.html' %}
{% block titulo %}
Editar Edificios
{% endblock %}
{% block contenido %}
<div class="container">
    <div class="card">
        <div class="card-header" style="background:darkkhaki;">
            Editar Edificios
        </div>
        <div class="card-body" style="background:bisque;">
          <h4 class="card-title">Datos del Edificio</h4>
   
           {% include "edificios/form.html" %}
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script>
$(document).ready(function() {

};
</script>
{% endblock %}

templates/edificios/form.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
      <div class="form-group">
          <label for="cuil">Nombre</label>
          <input id="nombre" class="form-control" type="text" name="nombre" value="{{ edificio.nombre }}">
      </div>
      <div class="form-group">
          <label for="domicilio">Domicilio</label>
          <input id="domicilio" class="form-control" type="text" name="domicilio" value="{{ edificio.domicilio }}">
      </div>

  <div class='mb-3 mt-3'>
  <input class="btn btn-primary btn-sm" type="submit" value="Guardar">
  <a href="{% url 'edificios:home' %}" class='btn btn-sm btn-danger'>Cancelar</a>
  </div>
</form>

templates/edificios/index.html
{% extends 'layout.html' %}
{% block titulo %}Edificios{% endblock %}
{% block contenido %}
    <div class="card">
        <div class="card-body">
            <p class="card-header h3">Listado de Edificios</p>
            <a href="{% url 'edificios:agregar' %}" class="btn btn-sm btn-primary mt-3 mb-3"><i class='fa fa-add'></i> Agregar</a>
            <table class="table table-striped table-sm table-success" id='edificios'>
                <thead class="table-dark">
                    <th>Nombre</th>
                    <th>Domicilio</th>
                    <th>Acciones</th>
                </thead>
                {% for e in edificios %}
                    <tr>
                        <td>{{ e.nombre }}</td>
                        <td>{{ e.domicilio }}</td>
                        <td>
                            <a href="editar/{{ e.id }}" class='btn btn-sm btn-success'><i class='fa fa-edit'></i> Editar</a>
                            <a href="eliminar/{{ e.id }}" class='btn btn-sm btn-danger'><i class='fa fa-trash'></i> Eliminar</a>
                    </tr>
                {% endfor%}
            </table>
        </div>
    </div>
{% endblock %}
{% block js %}
<script>
    $(document).ready(function() {
        $('#edificios').DataTable();
    });
</script>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}
{% load static %}
{% block titulo %}Consorcios - Home{% endblock %}
{% block contenido %}
<div class="row">
    <div class="col -4 text-center">
        <p class="h2 mt-3 mb-3">Sistema de Gestión de Consorcios</p>      
        <img src="{% static 'img/edificio.png' %}">  
    </div>

</div>
{% endblock %}
{% block js %}
{% endblock %}

templates/layout.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Bootstrap CSS -->
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.0/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css" rel="stylesheet" crossorigin="anonymous">

    <title>{% block titulo %}{% endblock %}</title>
</head>
<body>
    <div class="container">
    <nav class="navbar navbar-expand-lg bg-opacity-50 bg-success">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">Inicio</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
               
              <li class="nav-item">
                <a class="nav-link" href="{% url 'edificios:home' %}">Edificios</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#}">Propietarios</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Departamentos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Movimientos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Expensas</a>
              </li>
              {% comment %} <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li> {% endcomment %}
            </ul>
            <div class="col-md-3 text-end">
              <a href="{% url 'salir' %}" class="btn btn-danger btn-sm">{{ user.username }} <i class="fa-solid fa-right-from-bracket"></i></a>
            </div>
          </div>
        </div>
      </nav>
    {% block contenido %}
    {% endblock %}
    </div>
    <!-- Optional JavaScript; choose one of the two! -->
    
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>        
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
    {% block js %}{% endblock %}
</body>
</html>

templates/propietarios/agregar.html
{% extends 'layout.html' %}
{% block titulo %}
Agregar Propietario
{% endblock %}
{% block contenido %}
<div class="container">
    <div class="card">
        <div class="card-header" style="background:darkkhaki;">
            Agregar Propietario
        </div>
        <div class="card-body" style="background:bisque;">
          <h4 class="card-title">Datos del Propietario</h4>
   
           {% include "propietarios/form.html" %}
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script>
$(document).ready(function() {

};
</script>
{% endblock %}

templates/propietarios/editar.html
{% extends 'layout.html' %}
{% block titulo %}
Editar Propietarios
{% endblock %}
{% block contenido %}
<div class="container">
    <div class="card">
        <div class="card-header" style="background:darkkhaki;">
            Editar Propietarios
        </div>
        <div class="card-body" style="background:bisque;">
          <h4 class="card-title">Datos del Propietario</h4>
   
           {% include "propietarios/form.html" %}
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script>
$(document).ready(function() {

};
</script>
{% endblock %}

templates/propietarios/form.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
      <div class="form-group">
          <label for="cuil">Nombre</label>
          <input id="nombre" class="form-control" type="text" name="nombre" value="{{ propietario.nombre }}">
      </div>
      <div class="form-group">
          <label for="domicilio">Domicilio</label>
          <input id="domicilio" class="form-control" type="text" name="domicilio" value="{{ propietario.domicilio }}">
      </div>
      <div class="form-group">
        <label for="cuit_cuil">CUIT/CUIL</label>
        <input id="cuit_cuil" class="form-control" type="text" name="cuit_cuil" value="{{ propietario.cuit_cuil }}">
      </div>
        <div class="form-group">
        <label for="email">Correo Electrónico</label>
        <input id="email" class="form-control" type="text" name="email" value="{{ propietario.email }}">
      </div>

  <div class='mb-3 mt-3'>
  <input class="btn btn-primary btn-sm" type="submit" value="Guardar">
  <a href="{% url 'propietarios:home' %}" class='btn btn-sm btn-danger'>Cancelar</a>
  </div>
</form>

templates/propietarios/index.html
{% extends 'layout.html' %}
{% block titulo %}Propietarios{% endblock %}
{% block contenido %}
    <div class="card">
        <div class="card-body">
            <p class="card-header h3">Listado de Propietarios</p>
            <a href="{% url 'propietarios:agregar' %}" class="btn btn-sm btn-primary mt-3 mb-3"><i class='fa fa-add'></i> Agregar</a>
            <table class="table table-striped table-sm table-success" id='propietarios'>
                <thead class="table-dark">
                    <th>Nombre</th>
                    <th>Domicilio</th>
                    <th>Correo Electrónico</th>
                    <th>CUIT/CUIL</th>
                    <th>Acciones</th>
                </thead>
                {% for p in propietarios %}
                    <tr>
                        <td>{{ p.nombre }}</td>
                        <td>{{ p.domicilio }}</td>
                        <td>{{ p.email }}</td>
                        <td>{{ p.cuit_cuil }}</td>
                        <td>
                            <a href="editar/{{ p.id }}" class='btn btn-sm btn-success'><i class='fa fa-edit'></i> Editar</a>
                            <a href="eliminar/{{ p.id }}" class='btn btn-sm btn-danger'><i class='fa fa-trash'></i> Eliminar</a>
                    </tr>
                {% endfor%}
            </table>
        </div>
    </div>
{% endblock %}
{% block js %}
<script>
    $(document).ready(function() {
        $('#propietarios').DataTable();
    });
</script>
{% endblock %}